### ISSUE TITLE
Creating an information repository

### ISSUE THREAD

**Issue by mirober** [dictation-toolbox/dictation-toolbox#3]
@caspark suggested and I have been starting to put together a website to act as a repository for all accessible-computing related information. There is a lot of good information out there but it is currently scattered far and wide in individual blogs or gitter chat logs. The aim is to crystallise it in one place so that new users have somewhere they can go for information on voice coding, eye tracking, microphones, troubleshooting etc. 

It's currently on my GitHub pages and the repo is [here](https://github.com/mrob95/dictation-index). The site itself is [here](https://mrob95.github.io/dictation-index/).

What do you think about moving it to dictation-toolbox? It's at the stage where all it really needs (apart from a domain name) is more content written in markdown, and I'm hoping that the community will provide at least some of this.

**Comment by caspark** [comment]
FWIW I was thinking I would do this as a personal site (like @wolfmanstout 's site but less of a blog), but I'm currently busy with some other things, and I definitely think there's room for a community knowledge site too.

**Comment by calmofthestorm** [comment]
I would be happy to host that under dictation-toolbox.

**Comment by calmofthestorm** [comment]
My personal opinion is that the best place/format to host it is the one that makes it easy for people to contribute, so that up to date content is available. Whether that's a github repo, wiki, something else, etc I'm not really sure.

**Comment by mirober** [comment]
Sounds good. I think that GH is a good option to keep it together with the rest of dictation-toolbox and make it easy to contribute (I think you can fork, edit markdown and pull request all from within the browser).

I'm going to be busy over the next month or two with writing a dissertation and exams, but after that I'll have time to sink into making this a quality resource. 

How does the process work for transferring the repository to the new owner?

**Comment by nirvdrum** [comment]
I've registered and have been renewing dictation-toolbox.org for the past few years. I originally planned on adding resources like what's mentioned here and listing the various projects. I never found the time the first year and have just been renewing in hopes one day I would (and really so domain squatters wouldn't grab it).

I'd be happy to contribute that to the project here. Setting a gh-pages repo that any of us could update would be great.

**Comment by LexiconCode** [comment]
@mrob95 [Transferring A Repository Docs](https://help.github.com/en/articles/transferring-a-repository) It is pretty simple to transfer a repository to a new organization or owner. The only sensitive bit of the process is if owner doesn't accept the transfer within 24 hours, it won't complete.

**Comment by mirober** [comment]
@nirvdrum Hah! I checked to see if it was available and was disappointed to find that it wasn't, good stuff.

I'll initiate the transfer now and hopefully someone will get to it within 24 hours, over the weekend I'll adjust the layout to have pages for each of the dictation-toolbox utilities.

Edit: looks like I would need repository creation privileges. Can either do it that way or just make a new repository I guess.

**Comment by calmofthestorm** [comment]
Sent you an invite. Owner for now, not sure whether the plan is to leave everyone owner or do the owner/member split, then give members admin on their repos.

**Comment by LexiconCode** [comment]
Owners of the dictation-toolbox organization serve its purpose as originally discussed. Beyond that it would be nice to split people up into teams per project.

**Comment by calmofthestorm** [comment]
Fair enough; we'll call this temporary for the transfer then.

**Comment by calmofthestorm** [comment]
@mrob95 As noted, I removed the admin access to all of the organization; you should have admin on dictation-toolbox.org, and I *think* had preexisting write access to Caster. Let me know if I accidentally removed you from any other repositories you should have access to and I can fix it.
